### ISSUE TITLE
Not able to run on Windows system

### ISSUE THREAD

**Issue by r4onlyrishabh** [Skuldur/facenet-face-recognition#3]
Hi, 
I cloned your code and tried running on my system. 
The system throws the following error:

C:\>python D:\facenet-face-recognition-master\facenet.py
Using TensorFlow backend.
OpenCV Error: Assertion failed (!empty()) in cv::CascadeClassifier::detectMultiScale, file C:\ci\opencv_1512688052760\work\modules\objdetect\src\cascadedetect.cpp, line 1698
Traceback (most recent call last):
  File "D:\facenet-face-recognition-master\facenet.py", line 199, in <module>
    webcam_face_recognizer(database)
  File "D:\facenet-face-recognition-master\facenet.py", line 86, in webcam_face_recognizer
    img = process_frame(img, frame, face_cascade)
  File "D:\facenet-face-recognition-master\facenet.py", line 101, in process_frame
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
cv2.error: C:\ci\opencv_1512688052760\work\modules\objdetect\src\cascadedetect.cpp:1698: error: (-215) !empty() in function cv::CascadeClassifier::detectMultiScale

Please help!

I tried searching on stackOverflow. Here is what i found!!

https://stackoverflow.com/questions/30508922/error-215-empty-in-function-detectmultiscale?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

But this doesnt seem to help out!

**Comment by Rohitgarg253** [comment]
Try running using Anaconda distribution with all the requirements installed.

Worked on mine.
